### ISSUE TITLE
KeyError when using embeddings with no uuid in metadata

### ISSUE THREAD

**Issue by akb89** [annargrs/ldt#2]
I am experiencing an issue with this part of the`get_results` method in metadata.py: 
```python
for i in self.embeddings:
            emb_uuid = self._check_uuid_in_metadata(field="embeddings", path=i)
            if emb_uuid:
                self.metadata["timestamp"][emb_uuid] = {}
                self.metadata["timestamp"][emb_uuid]["start_time"] = \
                    datetime.datetime.now().isoformat()
            else:
                self.metadata["timestamp"][i]["start_time"] = \
                    datetime.datetime.now().isoformat()
```
I am using the embeddings dowloaded from [here](https://vecto.readthedocs.io/en/docs/tutorial/getting_vectors.html) more specifically `word_linear_cbow_500d` and `word_linear_sg_500d` which have no `uuid` in their metadata.json

The KeyError occurs in the `else` condition as `self.metadata["timestamp"][i]` is not initialized.

**Comment by akb89** [comment]
Note that this is easily solved by adding `self.metadata["timestamp"][i] = {}` (see below) but I don't know how robust this fix would be:
```python
for i in self.embeddings:
            emb_uuid = self._check_uuid_in_metadata(field="embeddings", path=i)
            if emb_uuid:
                self.metadata["timestamp"][emb_uuid] = {}
                self.metadata["timestamp"][emb_uuid]["start_time"] = \
                    datetime.datetime.now().isoformat()
            else:
                self.metadata["timestamp"][i] = {}
                self.metadata["timestamp"][i]["start_time"] = \
                    datetime.datetime.now().isoformat()
```

**Comment by annargrs** [comment]
I've applied this quick fix for now, and it's already in the master. It should only affect vecto embeddings, which we just haven't reformatted yet. If there's no metadata at all, uuid will be generated.
